# Generated by Django 5.2.4 on 2025-07-31 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='polls',
            name='option1',
            field=models.CharField(default='Option 1', max_length=200),
        ),
        migrations.AddField(
            model_name='polls',
            name='option2',
            field=models.CharField(default='Option 2', max_length=200),
        ),
    ]
