# Generated by Django 5.2.4 on 2025-08-01 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling_site', '0002_polls_option1_polls_option2'),
    ]

    operations = [
        migrations.AddField(
            model_name='polls',
            name='vote_count1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='polls',
            name='vote_count2',
            field=models.IntegerField(default=0),
        ),
    ]
